${.now?date}
${.now?time}
${.now}
${.now?string["MM月dd日HH时"]}
${cr?number?abs}
您放心用流量达到[n2]${total}G会降速，已用${(total?number - leftNum?number)?string('0.00')?replace('.00','')}G，系统已自动降速，网速下个账期自动恢复。

经查询，月初出账期扣了您本月的 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 当前实际扣费${sjkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。
查询您[n2]${plist[0].payDate?substring(4,6)}月${plist[0].payDate?substring(6,8)}号交了${plist[0].amount?number?string('0.00')?replace('.00','')}元话费，月初出账期扣除本月的 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 当前实际扣费${sjkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。
查询您[n2]${plist[0].payDate?substring(4,6)}月${plist[0].payDate?substring(6,8)}号共交了${pSum?string('0.00')?replace('.00','')}元话费， <#list plist as p>第${p_index+1}次交了${p.amount?number?string('0.00')?replace('.00','')}元<#if p_has_next>，<#else>。</#if></#list> 月初出账期扣除本月的 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 当前实际扣费${sjkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。
查询您月初一共交了${pSum?string('0.00')?replace('.00','')}元话费，其中 <#list plist as p>${p.payDate?substring(6,8)}号交了${p.amount?number?string('0.00')?replace('.00','')}元<#if p_has_next>，<#else>。</#if></#list> 月初出账期扣除本月的 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 当前实际扣费${sjkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。
查询您${month?substring(4,6)}月未达到协议消费补收${bsFee?string('0.00')?replace('.00','')}元，本月又扣了您 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 月初共扣费${ycgkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。
查询您[n2]${plist[0].payDate?substring(4,6)}月${plist[0].payDate?substring(6,8)}号交了${plist[0].amount?number?string('0.00')?replace('.00','')}元话费，${month?substring(4,6)}月未达到协议消费补收${bsFee?string('0.00')?replace('.00','')}元，本月又扣了您 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 月初共扣费${ycgkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。
查询您[n2]${plist[0].payDate?substring(4,6)}月${plist[0].payDate?substring(6,8)}号共交了${pSum?string('0.00')?replace('.00','')}元话费， <#list plist as p>第${p_index+1}次交了${p.amount?number?string('0.00')?replace('.00','')}元<#if p_has_next>，<#else>。</#if></#list>${month?substring(4,6)}月未达到协议消费补收${bsFee?string('0.00')?replace('.00','')}元，本月又扣了您 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 月初共扣费${ycgkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。
查询您月初一共交了${pSum?string('0.00')?replace('.00','')}元话费，其中 <#list plist as p>${p.payDate?substring(6,8)}号交了${p.amount?number?string('0.00')?replace('.00','')}元<#if p_has_next>，<#else>。</#if></#list>${month?substring(4,6)}月未达到协议消费补收${bsFee?string('0.00')?replace('.00','')}元，本月又扣了您 <#if tcgdf??>套餐及固定费${tcgdf?string('0.00')?replace('.00','')}元，</#if> <#if zzywf??>增值业务费${zzywf?string('0.00')?replace('.00','')}元，</#if> <#if bNeed??><#list bNeed as b>${b.billItemName}${b.fee?number?string('0.00')?replace('.00','')}元<#if b_has_next>，<#else>。</#if></#list></#if> <#if yhjm??>另外给您优惠减免了${yhjm?string('0.00')?replace('.00','')}元，</#if> 月初共扣费${ycgkf?string('0.00')?replace('.00','')}元，暂时没有其他扣费。